version: '3.8'
services:
  transcriber:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./whisper-models:/root/.cache/whisper
#    entrypoint: ["/bin/bash"]
#    # コンテナを起動したままにする
#    tty: true
#    stdin_open: true


