version: '3.8'
services:
  transcriber:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]